FROM python:3.10-slim

WORKDIR /

RUN pip install "poetry==1.3.1"



COPY poetry.lock pyproject.toml ./

RUN poetry config virtualenvs.create false \
    && poetry install --without dev --no-root



COPY . .

CMD ["python", "main.py","run"]




